name: Test EC2 Connection with GHA

on:
    workflow_dispatch

env:
    EC2_HOSTNAME: 3.36.68.26
    EC2_USERNAME: ubuntu
jobs:
    testec2-connet:
        name: test-ec2-connect
        runs-on: ubuntu-22.04

        steps:
            - name: setup SSH Directory
              run:
                mkdir -p ~/.ssh
                chmod 700 ~/.ssh
    
            - name: make private key file
              run: |
                echo "${{ secrets.EC2_PRIVATEKEY}}" > ~/.ssh/clouds2025_new.pem
                chmod 600 ~/.ssh/clouds2025_new.pem

            - name: test SSH connect to EC2
              env: 
                EC2_HOSTNAME: "3.36.68.26"
                EC2_USERNAME: "ubuntu"
              run: |
                echo "SSH 연결 테스트 시작...."

                ssh -vvv -o StrictHostKeyChecking=no \
                -O "UserKnownHostsFile=/dev/null" \
                -i ~/.ssh/clouds2025_new.pem -p 12138 \
                ${{env.EC2_USERNAME}}@${{env.EC2_HOSTNAME}} '
                    echo "현재 사용자: $(whoami)"'
                    echo "호스트명: $(hostname)"
                    echo "현재시간: $(date)"
                    echo "메모리 사용량" 
                    free -h                
                '

                

                echo "SSH 연결 테스트 종료...."
            - name: upload README.md vis SCP
              run: | 
                 echo "Hello, EC2SCP" > README.md

                 scp -i ~/.ssh/clouds2025_new.pem \
                 -o "StrictHostKeyChecking=no" \
                 -o "UserKnownHostsFile=/dev/null" \
                 -P 12138  README.md \
                 ${{env.EC2_USERNAME}}@${{env.EC2_HOSTNAME}}:~/



            - name: Cleanup private key
              if: always()
              run: |
                rm -f ~/.ssh/clouds2025_new.pem
