name: Test EC2 Connection with GHA

on:
    workflow_dispatch

jobs:
    testec2-connet:
        name: test-ec2-connect
        runs-on: ubuntu-22.04

        steps:
            - name: setup SSH Directory
              run:
                mkdir -p ~/.ssh
                chmod 700 ~/.ssh
    
            - name: make private key file
              run: |
                echo "${{ secrets.EC2_PRIVATEKEY}}" > ~/.ssh/ec2_key
                chmod 600 ~/.ssh/ec2_key

            - name: test SSH connect to EC2
              env: 
                HOSTNAME: "3.36.68.26"
                USER_NAME: "ubuntu"
              run: |
                echo "SSH 연결 테스트 시작...."

                ssh -vvv -o StrictHostKeyChecking=no \
                -O "UserKnownHostsFile=/dev/null" \
                -i ~/.ssh/ec2_key -p 22 \
                ${USER_NAME}@${HOSTNAME} '
                    echo "현재 사용자: $(whoami)"
                    echo "호스트명: $(hostname)"
                    echo "현재시간: $(date)"
                    echo "메모리 사용량" 
                    free -h
                EOF
                '

                echo "SSH 연결 테스트 종료...."
            
            - name: Cleanup private key
              if: always()
              run: |
                rm -f ~/.ssh/ec2_key
